# Generated by Django 2.1.4 on 2019-01-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190127_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrouprelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergrouprelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGroupRelation',
        ),
    ]
